"""Add a FK column

Revision ID: 2582ce34ad76
Revises: 29ad3afdb582
Create Date: 2025-11-07 19:05:51.472152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2582ce34ad76'
down_revision = '29ad3afdb582'
branch_labels = None
depends_on = None
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_students_course_id_courses', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_course_id_courses', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
