"""Add a new column in the Student table

Revision ID: b5a97e2ba25b
Revises: b6abfa188f0c
Create Date: 2025-11-03 19:27:36.289294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a97e2ba25b'
down_revision = 'b6abfa188f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
